# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'GoValet' do
    pod 'Alamofire', '~> 3.2.1'
    pod 'SwiftyJSON'
    pod 'MBProgressHUD’
    pod 'IQKeyboardManagerSwift'
    pod 'ReachabilitySwift'
    pod 'SDWebImage'
    pod 'KMPlaceholderTextView'
    pod 'SeparatorCollectionViewFlowLayout'
    pod 'DKImagePickerController'
    pod 'TOCropViewController'
    pod 'AJCountryPicker'
    pod 'DatePickerDialog'
    pod 'SlideMenuControllerSwift'
    pod 'Fusuma', '0.6.0'
    pod 'CameraManager', '~> 2.1.3'
    pod 'MICountryPicker', :git => 'https://github.com/mustafaibrahim989/MICountryPicker.git', :branch => 'swift-2'
    pod "CameraEngine"
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoValet

  target 'GoValetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoValetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
